---
name: CI

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        node: [16, 18]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}
          path: node_modules
      - name: Installing dependencies
        run: yarn install
      - name: Format
        run: |
          yarn format
          yarn format:md
      - name: Lint
        run: |
          yarn lint
          yarn lint:editorconfig
          yarn lint:jscpd
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
